/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { SignedZone } from "./SignedZone";
export type { SignedZoneController } from "./SignedZoneController";
