/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "Breakwater",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Breakwater__factory>;
    getContractFactory(
      name: "SIP5Interface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SIP5Interface__factory>;
    getContractFactory(
      name: "SIP7Interface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SIP7Interface__factory>;
    getContractFactory(
      name: "ZoneInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ZoneInterface__factory>;
    getContractFactory(
      name: "SIP7Zone",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SIP7Zone__factory>;

    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "Breakwater",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Breakwater>;
    getContractAt(
      name: "SIP5Interface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.SIP5Interface>;
    getContractAt(
      name: "SIP7Interface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.SIP7Interface>;
    getContractAt(
      name: "ZoneInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ZoneInterface>;
    getContractAt(
      name: "SIP7Zone",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.SIP7Zone>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
