/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "CancelX",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CancelX__factory>;
    getContractFactory(
      name: "ZoneInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ZoneInterface__factory>;
    getContractFactory(
      name: "ICancelX",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICancelX__factory>;

    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "CancelX",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CancelX>;
    getContractAt(
      name: "ZoneInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ZoneInterface>;
    getContractAt(
      name: "ICancelX",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ICancelX>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
