/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IMultiX,
  IMultiXInterface,
} from "../../../src/interfaces/IMultiX";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "signer",
        type: "address",
      },
    ],
    name: "setSigner",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "signer",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMultiX__factory {
  static readonly abi = _abi;
  static createInterface(): IMultiXInterface {
    return new utils.Interface(_abi) as IMultiXInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMultiX {
    return new Contract(address, _abi, signerOrProvider) as IMultiX;
  }
}
