/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IBreakwater__factory } from "./IBreakwater__factory";
export { IMultiX__factory } from "./IMultiX__factory";
